### ISSUE TITLE
Add top-level LICENSE file?

### ISSUE THREAD

**Issue by jakerockland** [intartnft/scripty.sol#2]
Hello!

Any chance we could get a top-level LICENSE file associated with this repo?

Looking at https://github.com/intartnft/scripty.sol/blob/28cc612d7dc3a709f35c534c981bfc6bbfce4209/contracts/scripty/utils/AddressChunks.sol it looks like license for the solidity files here at least is MIT, wondering if the whole repo may be considered MIT?

**Comment by xtremetom** [comment]
@0xdude and I have no issue making the whole thing MIT
Will add a top level license to that effect
Have fun with it

**Comment by jakerockland** [comment]
Fantastic!! Thank you 🙏

**Comment by xtremetom** [comment]
https://github.com/intartnft/scripty.sol/blob/main/MIT-LICENSE.txt
