### ISSUE TITLE
Deployment on additional chains

### ISSUE THREAD

**Issue by miracle2k** [intartnft/scripty.sol#3]
Can we get scripty deployed "officially" on more EVM chains? I'm happy to contribute / pay for the gas (I think! I hope I am not underestimating the cost :))

I am particularly interested in:
- Sepolia
- Optimism Mainnet
- Optimism Goerli
- Avalanche
- Arbitrum
- Polygon

**Comment by xtremetom** [comment]
I don't see any reason why not

**Comment by miracle2k** [comment]
@xtremetom @0xdude how can we get it done? should I do the deployments + an MR to the repo with the addresses?

**Comment by xtremetom** [comment]
I suspect we will fire this off. I am away on holiday right now so will address when I return

**Comment by 0xdude** [comment]
@miracle2k I'll look into this this weekend. Maybe we can prioritise some of the other chains first. What do you think?

**Comment by miracle2k** [comment]
@0xdude What do you mean by "other"? I have the biggest need for Ethereum, Avalanche, Optimism and Polygon, but any work you'd be doing on this is much appreciated, and happy to help in any way I can. 

Actually, one of the challenges here might be that ethfs itself is required, but not really available anywhere it seems. :(

**Comment by 0xdude** [comment]
@miracle2k after a massive delay, I deployed scripty.sol to:
Sepolia
Base, Base Sepolia 
Optimism, Optimism Sepolia.

**Comment by jwahdatehagh** [comment]
i just deployed the contracts to Holesky:

- [ScriptyBuilder](https://holesky.etherscan.io/address/0xD7587F110E08F4D120A231bA97d3B577A81Df022#code)
- [ScriptyStorage](https://holesky.etherscan.io/address/0xbD11994aABB55Da86DC246EBB17C1Be0af5b7699#code)
- [EthFsV2FileStorage](https://holesky.etherscan.io/address/0x8FAA1AAb9DA8c75917C43Fb24fDdb513edDC3245#code)

```json
{
    "ScriptyBuilderV2": "0xD7587F110E08F4D120A231bA97d3B577A81Df022",
    "ScriptyStorageV2": "0xbD11994aABB55Da86DC246EBB17C1Be0af5b7699",
    "ETHFSV2FileStorage": "0x8FAA1AAb9DA8c75917C43Fb24fDdb513edDC3245"
}
```

**Comment by 0xdude** [comment]
Thanks for this @jwahdatehagh 

Closing the issue for now as we support multiple popular chains.
