### ISSUE TITLE
Smart Contracts Not Appearing on OpenSea After Deployment

### ISSUE THREAD

**Issue by PaulCelanCoding** [intartnft/scripty.sol#4]
Description:
We've encountered a critical issue with the scripty.sol library as we approach our project release. Despite following the deployment procedures that worked previously, our smart contracts are not visible on OpenSea. This issue is not isolated to our custom contracts; it also affects the example contracts provided within the library's repository.

Steps to Reproduce:

npx hardhat run examples/randomShapes/deploy.js --network --goerli
Search for the deployed NFTs on OpenSea.

Expected Behavior:
The deployed smart contracts should be visible and verifiable on OpenSea as they have been in the past.

Actual Behavior:
The deployed smart contracts do not appear on OpenSea, neither through direct search nor through the OpenSea verification process. This issue persists even with the example contracts from the scripty.sol library.

Additional Information:

This sudden change in behavior is puzzling since the deployment and verification steps have not changed, and they previously resulted in the contracts appearing on OpenSea without issue.
We are working with a tight deadline and are eager to resolve this issue promptly.

Questions:

Has anyone experienced a similar issue with smart contracts not appearing on OpenSea after deployment using the scripty.sol library?
Are there specific details or log information that would be particularly helpful for troubleshooting this issue?
Any insights, advice, or suggestions on how to address this problem would be greatly appreciated.
Thank you in advance for any help or guidance you can provide. We are looking forward to your suggestions and are happy to provide any additional information that might help resolve this issue.

**Comment by 0xdude** [comment]
Hello!

Thanks for using scripty.sol! Recently OpenSea dropped supporting Goerli. I suggest you to switch to Sepolia. 

Also, scripty.sol went under some updates but changes are not merged to main branch yet. You can check the changes [here](https://github.com/intartnft/scripty.sol/tree/scripty-v3).

In that branch, you will see that all the examples are upgraded to Sepolia and we upgraded our storage solution and EthFS V2 storage wrapper to EthFS V2.
